package br.org.webgov.model;
// Generated 05/11/2011 21:00:09 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;

/**
 * Papel generated by hbm2java
 */
@Entity
@Table(name = "papel", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "nome"))
public class Papel implements java.io.Serializable {

	private int id;
	private String nome;
	private String descricao;
	private Set<UsuarioPapel> usuarioPapels = new HashSet<UsuarioPapel>(0);

	public Papel() {
	}

	public Papel(int id) {
		this.id = id;
	}
	public Papel(int id, String nome, String descricao,
			Set<UsuarioPapel> usuarioPapels) {
		this.id = id;
		this.nome = nome;
		this.descricao = descricao;
		this.usuarioPapels = usuarioPapels;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nome", unique = true, length = 20)
	@Length(max = 20)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao")
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "papel")
	public Set<UsuarioPapel> getUsuarioPapels() {
		return this.usuarioPapels;
	}

	public void setUsuarioPapels(Set<UsuarioPapel> usuarioPapels) {
		this.usuarioPapels = usuarioPapels;
	}

}
