package br.org.webgov.model;
// Generated 05/11/2011 21:00:09 by Hibernate Tools 3.2.4.GA

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuarioPapel generated by hbm2java
 */
@Entity
@Table(name = "usuario_papel", schema = "public")
public class UsuarioPapel implements java.io.Serializable {

	private UsuarioPapelId id;
	private Usuario usuario;
	private Papel papel;

	public UsuarioPapel() {
	}

	public UsuarioPapel(UsuarioPapelId id) {
		this.id = id;
	}
	public UsuarioPapel(UsuarioPapelId id, Usuario usuario, Papel papel) {
		this.id = id;
		this.usuario = usuario;
		this.papel = papel;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUsuario", column = @Column(name = "id_usuario")),
			@AttributeOverride(name = "idPapel", column = @Column(name = "id_papel"))})
	public UsuarioPapelId getId() {
		return this.id;
	}

	public void setId(UsuarioPapelId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_papel", insertable = false, updatable = false)
	public Papel getPapel() {
		return this.papel;
	}

	public void setPapel(Papel papel) {
		this.papel = papel;
	}

}
