package br.org.webgov.model;
// Generated 05/11/2011 21:00:09 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.validator.Length;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "public", uniqueConstraints = {
		@UniqueConstraint(columnNames = "titulo_eleitoral"),
		@UniqueConstraint(columnNames = "username")})
public class Usuario implements java.io.Serializable {

	private int id;
	private String nome;
	private String password;
	private Boolean ativo;
	private Integer tituloEleitoral;
	private String username;
	private Set<UsuarioPapel> usuarioPapels = new HashSet<UsuarioPapel>(0);

	public Usuario() {
	}

	public Usuario(int id) {
		this.id = id;
	}
	public Usuario(int id, String nome, String password, Boolean ativo,
			Integer tituloEleitoral, String username,
			Set<UsuarioPapel> usuarioPapels) {
		this.id = id;
		this.nome = nome;
		this.password = password;
		this.ativo = ativo;
		this.tituloEleitoral = tituloEleitoral;
		this.username = username;
		this.usuarioPapels = usuarioPapels;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "nome", length = 50)
	@Length(max = 50)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "password", length = 30)
	@Length(max = 30)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ativo")
	public Boolean getAtivo() {
		return this.ativo;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}

	@Column(name = "titulo_eleitoral", unique = true)
	public Integer getTituloEleitoral() {
		return this.tituloEleitoral;
	}

	public void setTituloEleitoral(Integer tituloEleitoral) {
		this.tituloEleitoral = tituloEleitoral;
	}

	@Column(name = "username", unique = true, length = 30)
	@Length(max = 30)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioPapel> getUsuarioPapels() {
		return this.usuarioPapels;
	}

	public void setUsuarioPapels(Set<UsuarioPapel> usuarioPapels) {
		this.usuarioPapels = usuarioPapels;
	}

}
