package br.org.webgov.model;
// Generated 05/11/2011 21:00:09 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsuarioPapelId generated by hbm2java
 */
@Embeddable
public class UsuarioPapelId implements java.io.Serializable {

	private Integer idUsuario;
	private Integer idPapel;

	public UsuarioPapelId() {
	}

	public UsuarioPapelId(Integer idUsuario, Integer idPapel) {
		this.idUsuario = idUsuario;
		this.idPapel = idPapel;
	}

	@Column(name = "id_usuario")
	public Integer getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Integer idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "id_papel")
	public Integer getIdPapel() {
		return this.idPapel;
	}

	public void setIdPapel(Integer idPapel) {
		this.idPapel = idPapel;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsuarioPapelId))
			return false;
		UsuarioPapelId castOther = (UsuarioPapelId) other;

		return ((this.getIdUsuario() == castOther.getIdUsuario()) || (this
				.getIdUsuario() != null
				&& castOther.getIdUsuario() != null && this.getIdUsuario()
				.equals(castOther.getIdUsuario())))
				&& ((this.getIdPapel() == castOther.getIdPapel()) || (this
						.getIdPapel() != null
						&& castOther.getIdPapel() != null && this.getIdPapel()
						.equals(castOther.getIdPapel())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		result = 37 * result
				+ (getIdPapel() == null ? 0 : this.getIdPapel().hashCode());
		return result;
	}

}
